# Baseline — Cenário 1: CSV simples

**Objetivo:** implementar manualmente o mesmo pipeline do Cenário 1 em pandas puro,  
para servir de linha de base comparativa com o AI-ETL.

**Spec equivalente:**  
> Leia `case_study/data/sales.csv`. Renomeie `dt` → `date` e `amt` → `amount`. Filtre `status == 'active'`. Remova duplicatas. Salve em `case_study/results/scenario1/output_baseline.csv`.

---

## Métricas de implementação (registradas manualmente)

| Métrica | Valor |
|---|---|
| Tempo de implementação | ~4 min |
| Linhas de código (excl. comentários e markdown) | ver célula final |
| Decisões explícitas necessárias | 3 (nomes das colunas, coluna de status, destino) |
| Erros durante desenvolvimento | 0 (spec clara para quem conhece pandas) |
| Iterações até resultado correto | 1 |

In [1]:
import time
from pathlib import Path

import pandas as pd

start = time.time()

### 1. Extração

In [2]:
df = pd.read_csv("../data/sales.csv")
print(f"Loaded: {df.shape}")
df.head(3)

Loaded: (5000, 8)

,order_id,customer_id,dt,product,amt,qty,status,region
0,2502,204.0,2024-05-05,Gadget Y,111.76,18,active,Sul
1,3587,NaN,2024-08-03,Tool Z,139.52,19,active,Sudeste
2,3654,249.0,2024-08-09,Gadget Y,118.37,7,active,Centro-Oeste

### 2. Transformação

In [3]:
# Rename columns
df = df.rename(columns={"dt": "date", "amt": "amount"})

# Filter active only
df = df[df["status"] == "active"]

# Remove duplicates
df = df.drop_duplicates().reset_index(drop=True)

print(f"After transform: {df.shape}")
df.head(3)

After transform: (3649, 8)

,order_id,customer_id,date,product,amount,qty,status,region
0,2502,204.0,2024-05-05,Gadget Y,111.76,18,active,Sul
1,3587,NaN,2024-08-03,Tool Z,139.52,19,active,Sudeste
2,3654,249.0,2024-08-09,Gadget Y,118.37,7,active,Centro-Oeste

### 3. Qualidade (manual)

In [4]:
null_report = df.isnull().mean().round(4)
dup_count = df.duplicated().sum()

print("Null ratios:")
print(null_report[null_report > 0])
print(f"\nDuplicates remaining: {dup_count}")

Null ratios:
customer_id    0.0534
amount         0.0493
dtype: float64

Duplicates remaining: 0

### 4. Carga

In [5]:
out_path = Path("../results/scenario1/output_baseline.csv")
out_path.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(out_path, index=False)

elapsed = time.time() - start
print(f"Saved {len(df)} rows → {out_path}")
print(f"Pipeline execution time: {elapsed:.2f}s")

Saved 3649 rows → ../results/scenario1/output_baseline.csv
Pipeline execution time: 0.10s

---
## Resumo de métricas

In [6]:
code_lines = 9  # linhas de código Python acima (excl. prints e imports)

print("=" * 50)
print("BASELINE — Cenário 1")
print("=" * 50)
print(f"Rows output:              {len(df)}")
print(f"Execution time:           {elapsed:.2f}s")
print(f"LOC written:              {code_lines}")
print(f"Explicit decisions:       3")
print(f"Dev errors (tracebacks):  0")
print(f"Iterations to correct:    1")
print()
print("AI-ETL (avg of 5 runs):")
print(f"  Execution time:         10.6s")
print(f"  LOC written by human:   0 (spec in NL)")
print(f"  LLM attempts:           2.0")
print(f"  Human interventions:    0")

==================================================
BASELINE — Cenário 1
==================================================
Rows output:              3649
Execution time:           0.10s
LOC written:              9
Explicit decisions:       3
Dev errors (tracebacks):  0
Iterations to correct:    1

AI-ETL (avg of 5 runs):
  Execution time:         10.6s
  LOC written by human:   0 (spec in NL)
  LLM attempts:           2.0
  Human interventions:    0